# Import bibliotek

In [1]:
import numpy as np
import pandas as pd

# Zdobycie danych

In [2]:
folder_name = 'dane/dane_sample'

## 1. Temperatura elektrolitu w obiegach cyrkulacyjnych

In [3]:
temp_naporowe = pd.read_excel(f'{folder_name}/1. Temperatura elektrolitu w obiegach cyrkulacyjnych.xlsx',
                              sheet_name='Zbiorniki naporowe')
temp_naporowe

,Data,Obieg 1,Obieg 2,Obieg 3,Obieg 4,Obieg 5,Obieg 6,Obieg 7,Obieg 8,Obieg 9,Obieg 10,Obieg 11,Obieg 12
0,2021-03-01 00:00:00,60.328833,61.581333,59.399984,60.996766,60.653533,58.968817,60.132350,60.016834,60.465333,61.092733,61.029150,60.234767
1,2021-03-01 01:00:00,60.128667,61.725417,59.436183,61.013983,60.403250,59.036050,59.762117,59.993484,60.454833,61.187183,60.974350,60.189700
2,2021-03-01 02:00:00,60.120800,61.905533,59.546199,60.378500,60.190567,59.151250,59.783999,60.003367,60.370650,61.230833,60.543484,60.138833
3,2021-03-01 03:00:00,60.719817,61.807434,59.688650,60.144100,59.791417,59.446634,59.826083,60.017767,60.478800,60.777716,60.330933,60.082417
4,2021-03-01 04:00:00,60.064250,61.597867,60.009667,59.954333,59.949700,59.455317,59.831699,59.761600,60.149850,60.278834,60.184633,60.058966
5,2021-03-01 05:00:00,59.861500,61.112733,60.156083,59.806800,59.857084,59.375267,59.931333,60.155884,59.986883,60.410450,60.049100,60.039383
6,2021-03-01 06:00:00,59.758400,60.784950,59.849734,59.663583,59.682000,59.299234,59.609800,59.776700,60.133300,60.202250,60.002450,60.054517
7,2021-03-01 07:00:00,59.782763,60.262305,59.302152,59.405322,59.406271,59.167288,59.158695,59.635763,59.975475,60.085187,59.952102,59.779797
8,2021-03-01 08:00:00,59.730133,60.419100,59.706733,59.474767,59.448683,59.346100,59.242950,59.889233,59.616767,60.224750,59.490483,59.716384
9,2021-03-01 09:00:00,59.841083,60.759150,60.371117,60.032800,59.823633,59.502217,59.520833,59.935650,59.058800,60.217716,59.496417,59.703200
10,2021-03-01 10:00:00,59.958183,60.427183,59.752900,60.492333,60.716850,60.116867,59.634617,60.033151,59.744516,60.250133,59.817150,59.762950
11,2021-03-01 11:00:00,61.198733,60.407366,59.515083,59.787916,60.612767,60.810533,60.524000,60.105783,59.656417,60.252616,60.127233,59.884450
12,2021-03-01 12:00:00,60.574066,61.240000,58.806084,59.616167,59.938317,61.295933,60.567233,60.178450,59.897317,60.314883,59.756783,60.018433
13,2021-03-01 13:00:00,59.741150,60.408600,58.743800,57.325800,59.858700,62.043300,60.618516,60.354283,60.499166,60.410534,57.917466,60.058583
14,2021-03-01 14:00:00,59.706150,59.798217,58.708034,57.389500,59.784383,61.240783,60.295500,60.337717,60.970950,60.385867,60.271466,60.068783
15,2021-03-01 15:00:00,59.648350,59.758433,58.629817,57.216900,59.800584,61.285950,60.209417,60.802833,61.102133,60.223033,59.741367,59.057133
16,2021-03-01 16:00:00,59.760917,59.880900,58.700234,58.249050,59.934200,61.041450,60.225567,60.524083,60.333800,60.271033,59.599950,57.639967
17,2021-03-01 17:00:00,59.816516,60.337950,58.703750,59.725683,59.999184,61.077783,60.207017,60.139117,60.075117,60.242383,60.256467,58.710133
18,2021-03-01 18:00:00,60.020733,60.498350,58.743700,59.318766,59.913984,61.062283,60.247201,60.022167,59.987500,60.357283,61.008550,59.616550
19,2021-03-01 19:00:00,60.390300,59.786750,58.592666,58.960617,59.994834,60.839367,60.242067,60.139983,59.687600,60.522067,60.589917,60.652050
20,2021-03-01 20:00:00,60.892333,59.663200,58.364217,59.287333,60.105884,60.535717,60.480883,60.385650,59.836316,61.099783,60.445317,60.059833
21,2021-03-01 21:00:00,60.408067,59.967017,58.102417,59.587967,60.110067,60.031233,60.210850,60.338983,59.942500,61.479267,59.730150,60.336867
22,2021-03-01 22:00:00,60.270133,59.740300,58.155250,59.775300,60.090983,59.862300,60.095034,59.413033,59.927917,61.167650,59.806750,60.076417
23,2021-03-01 23:00:00,59.843067,60.006283,57.955000,59.865716,60.302400,59.761850,59.996133,60.279117,60.192783,60.935683,60.004416,60.073884

In [4]:
temp_cyrkulacyjne = pd.read_excel(f'{folder_name}/1. Temperatura elektrolitu w obiegach cyrkulacyjnych.xlsx',
                                  sheet_name='Zbiorniki cyrkulacyjne')
temp_cyrkulacyjne

,Data,Obieg 1,Obieg 2,Obieg 3,Obieg 4,Obieg 5,Obieg 6,Obieg 7,Obieg 8,Obieg 9,Obieg 10,Obieg 11,Obieg 12
0,2021-03-01 00:00:00,55.990900,56.590016,56.969033,56.810783,57.047266,54.709050,57.675967,59.250783,55.937700,57.926967,57.303367,58.198767
1,2021-03-01 01:00:00,55.842916,56.881200,56.819816,57.920000,57.078599,54.810350,57.617949,59.232583,56.032250,58.090117,57.781283,58.200733
2,2021-03-01 02:00:00,55.910084,57.229567,56.734916,57.808867,56.999050,54.899017,57.613583,59.214351,56.186800,58.239417,57.919334,58.196083
3,2021-03-01 03:00:00,56.558600,57.532000,56.216150,57.701983,56.693234,55.223584,57.591900,59.200817,56.626767,58.327000,57.939200,58.198000
4,2021-03-01 04:00:00,55.991817,57.815767,56.632083,57.562767,56.852717,55.193133,57.587500,58.686800,56.556617,58.064817,57.919817,58.179033
5,2021-03-01 05:00:00,55.788767,57.746100,56.708800,57.408667,56.675200,55.092566,57.586884,59.168000,56.479033,58.242667,57.831817,58.167716
6,2021-03-01 06:00:00,55.660217,57.166833,56.212450,57.082400,56.397500,54.995783,57.084267,58.370233,56.325500,58.007317,57.712767,58.201533
7,2021-03-01 07:00:00,55.707237,56.741949,55.749559,56.594780,56.030593,54.954390,56.470424,57.765797,56.125424,57.917780,57.692356,57.945492
8,2021-03-01 08:00:00,55.593083,56.731317,55.683950,56.357350,55.949600,55.181650,56.101333,57.612533,55.425667,58.058450,57.414267,57.834550
9,2021-03-01 09:00:00,55.603533,56.717133,56.041600,57.073050,56.007600,55.299150,56.065351,57.530433,55.077500,58.090984,57.214550,57.706733
10,2021-03-01 10:00:00,55.719717,56.569883,55.514467,57.048650,57.212033,55.710933,56.263483,57.668500,55.269583,58.127467,57.263950,57.654450
11,2021-03-01 11:00:00,57.286183,56.692500,56.172733,56.655483,56.698500,56.415367,56.926683,57.824083,55.104350,58.194084,57.305550,57.715633
12,2021-03-01 12:00:00,56.469833,57.982550,56.152117,56.301883,56.342200,57.042167,57.257650,58.069950,55.384266,58.198916,57.125317,57.790716
13,2021-03-01 13:00:00,55.972616,57.208217,56.040567,53.688100,56.267317,57.703450,57.588200,58.577400,56.071383,58.154833,54.558450,57.845616
14,2021-03-01 14:00:00,55.882283,56.814466,56.064101,54.024567,56.235750,57.053933,57.641850,59.038150,56.907200,58.190550,56.803834,57.893617
15,2021-03-01 15:00:00,55.789301,56.682517,56.024384,52.854900,56.247701,57.249433,57.777517,60.739317,57.831900,58.216317,55.911800,57.670584
16,2021-03-01 16:00:00,55.745251,56.640283,55.986184,54.589467,56.275367,56.898834,57.876167,60.033383,57.953633,58.248650,55.734183,57.575650
17,2021-03-01 17:00:00,55.763217,57.275900,55.975334,55.892667,56.340467,57.121350,57.951450,59.857667,57.972217,58.279100,56.554983,57.200917
18,2021-03-01 18:00:00,55.876983,57.625750,55.945466,54.506433,56.126067,57.266583,58.005234,59.823767,57.905667,58.285917,57.370883,57.349150
19,2021-03-01 19:00:00,55.936483,56.933883,55.816167,54.438700,56.411983,57.444250,58.027683,60.044150,57.445233,58.340333,57.365850,57.943450
20,2021-03-01 20:00:00,56.635417,56.699267,55.470783,54.728083,56.452983,57.485283,58.313500,60.447167,57.356383,58.754900,57.422017,57.741067
21,2021-03-01 21:00:00,56.325550,56.981150,55.167683,55.036500,56.467783,57.158733,58.104317,60.480983,57.301666,58.849883,57.075167,57.980650
22,2021-03-01 22:00:00,56.147017,56.613600,55.406783,55.258150,55.810267,56.977500,58.029667,59.274983,56.867116,58.734934,57.041216,57.920601
23,2021-03-01 23:00:00,56.006100,56.636117,55.223317,55.321033,56.327934,56.762900,57.972983,60.136267,57.382200,58.818384,57.196017,57.977783

## 2. Poziom elektrolitu w zbiornikach

In [5]:
poziom_naporowe = pd.read_excel(f'{folder_name}/2. Poziom elektrolitu w zbiornikach .xlsx',
                                sheet_name='Zbiorniki naporowe')
poziom_naporowe

,Data,Obieg 1,Obieg 2,Obieg 3,Obieg 4,Obieg 5,Obieg 6,Obieg 7,Obieg 8,Obieg 9,Obieg 10,Obieg 11,Obieg 12
0,2021-03-01 00:00:00,74.998100,74.980116,74.993550,75.283817,74.987700,74.998983,75.005700,75.002400,74.983417,75.001466,75.009767,75.001317
1,2021-03-01 01:00:00,74.997317,75.016417,75.002800,74.997250,74.997317,74.993884,74.967583,75.004167,74.936884,74.985900,74.998583,74.991183
2,2021-03-01 02:00:00,75.002150,74.980083,74.999150,74.998166,75.007133,74.996683,74.962533,74.995400,74.935033,75.007167,74.994667,74.994284
3,2021-03-01 03:00:00,75.008133,74.993066,75.012817,74.994050,75.011050,75.007367,74.984517,75.002150,74.980500,74.998483,75.001183,75.000567
4,2021-03-01 04:00:00,74.996733,74.989150,75.005834,75.000883,74.994800,74.996717,74.988851,75.015083,74.976800,75.019250,74.997266,74.989266
5,2021-03-01 05:00:00,74.989400,75.014517,74.999967,74.995733,75.002950,74.997500,75.005450,74.998600,74.999383,74.992667,75.001783,75.002283
6,2021-03-01 06:00:00,75.005017,74.986500,74.971300,74.995767,74.967400,75.011233,75.007150,74.997617,75.193283,75.015300,75.004984,75.017850
7,2021-03-01 07:00:00,75.012187,75.002254,74.995695,75.006085,74.995119,74.982203,75.019814,74.992576,75.035830,74.990779,75.001695,75.001847
8,2021-03-01 08:00:00,74.997900,74.997117,75.019467,74.995983,75.014317,74.998600,74.991966,74.995134,74.763517,74.986017,74.994833,75.002383
9,2021-03-01 09:00:00,74.995116,74.989550,75.006400,75.035000,74.992267,75.020850,74.994133,74.990733,75.054784,74.990583,75.027201,74.995050
10,2021-03-01 10:00:00,75.002850,74.989467,75.013017,75.004050,75.012633,75.138350,75.019684,74.999850,74.983217,74.985500,74.974384,74.985417
11,2021-03-01 11:00:00,75.037750,74.987317,74.998733,74.996400,75.010684,75.000700,75.009000,75.004183,75.064050,74.997283,75.131217,75.010534
12,2021-03-01 12:00:00,75.006150,75.031383,74.999450,74.793750,74.996450,74.791400,74.983117,74.999484,75.005800,74.992734,74.589800,74.989783
13,2021-03-01 13:00:00,75.002700,74.994867,74.998583,74.953200,74.994667,75.019000,74.999483,74.994650,74.947283,74.987834,75.037183,74.994600
14,2021-03-01 14:00:00,74.994933,74.989400,74.994784,74.889267,75.002183,74.997350,74.982534,74.952433,74.994834,74.997017,75.019550,75.000767
15,2021-03-01 15:00:00,74.995050,74.994367,74.998517,75.012500,74.986950,74.997134,74.968500,75.015184,75.030783,75.006916,74.999666,32.444233
16,2021-03-01 16:00:00,75.002233,74.852166,74.998500,75.009517,75.005133,74.996417,74.997467,75.023550,75.064417,75.009350,74.997701,6.460450
17,2021-03-01 17:00:00,74.998083,75.129316,75.002667,75.041084,75.011233,74.996217,75.003133,75.008233,74.969500,74.989700,75.011383,66.567467
18,2021-03-01 18:00:00,74.998634,75.005033,74.994483,75.004300,75.011100,74.995650,74.998667,74.835233,74.930866,74.995833,75.020933,68.217400
19,2021-03-01 19:00:00,74.997550,74.988716,74.999684,74.997350,74.997367,75.023650,74.997900,75.152550,74.979034,75.003883,75.006017,75.027700
20,2021-03-01 20:00:00,75.012517,74.993317,75.020633,74.997167,74.998600,75.003834,74.986750,75.008300,75.013117,75.005667,74.994134,75.000750
21,2021-03-01 21:00:00,74.999850,75.010584,75.002634,74.994383,74.878283,74.997333,75.002234,74.802834,74.775766,75.008167,74.999883,75.014917
22,2021-03-01 22:00:00,74.994217,75.016200,74.998883,74.999300,75.034533,74.999317,75.019950,75.171817,75.126616,74.988400,74.996067,74.989983
23,2021-03-01 23:00:00,74.998083,74.997950,74.996050,75.004200,75.307350,74.997234,74.982000,75.000933,75.231467,75.003483,75.000583,74.996650

In [6]:
poziom_cyrkulacyjne = pd.read_excel(f'{folder_name}/2. Poziom elektrolitu w zbiornikach .xlsx',
                                    sheet_name='Zbiorniki cyrkulacyjne')
poziom_cyrkulacyjne

,Data,Obieg 1,Obieg 2,Obieg 3,Obieg 4,Obieg 5,Obieg 6,Obieg 7,Obieg 8,Obieg 9,Obieg 10,Obieg 11,Obieg 12
0,2021-03-01 00:00:00,82.159433,87.158700,83.181100,77.839017,82.536900,84.035583,89.264534,83.620916,83.907100,83.534167,89.922283,84.014200
1,2021-03-01 01:00:00,79.679267,86.654016,81.632900,85.593784,80.751267,83.089000,88.198733,82.156567,82.119033,81.766667,89.751450,82.788367
2,2021-03-01 02:00:00,79.430033,86.014734,80.182367,84.594200,78.921183,81.601733,87.081334,80.747916,80.264383,80.023067,89.170317,81.594100
3,2021-03-01 03:00:00,88.069933,85.334267,83.297884,83.622099,81.164533,83.624284,85.796183,79.341650,81.746583,78.234050,88.617066,80.325583
4,2021-03-01 04:00:00,85.905633,84.477483,86.862617,82.539650,82.240066,83.401767,84.552733,80.953734,80.296567,79.534283,88.119333,79.212650
5,2021-03-01 05:00:00,83.366533,83.319284,87.059500,81.330083,80.566983,81.899700,83.435051,83.578300,78.163900,82.153150,87.656067,78.334933
6,2021-03-01 06:00:00,79.796967,82.757750,79.038517,80.049299,75.815150,86.199700,78.211034,87.128500,83.772833,89.341734,92.338966,90.107333
7,2021-03-01 07:00:00,74.206119,82.114814,69.695678,74.835882,68.385424,87.243695,78.038746,86.354848,85.714306,89.112576,92.678441,91.381864
8,2021-03-01 08:00:00,70.406000,80.245666,76.252867,73.493133,71.314400,85.927100,77.545800,84.577984,78.973300,87.660733,91.564967,90.258017
9,2021-03-01 09:00:00,65.716783,78.829900,77.527333,83.846584,75.642783,84.615050,77.255600,82.793450,84.814350,85.863066,90.533183,89.042450
10,2021-03-01 10:00:00,64.185517,76.534900,85.421333,89.857734,73.384817,86.884383,85.507883,81.086501,84.736417,84.369549,85.248017,88.152917
11,2021-03-01 11:00:00,81.546483,73.288167,84.988067,88.599600,82.538817,87.078683,85.698883,80.642917,79.945700,82.833367,81.049883,87.243717
12,2021-03-01 12:00:00,90.112100,82.968867,87.441967,88.549000,81.058817,78.069016,87.895083,80.402967,79.405067,81.147333,77.532566,86.270267
13,2021-03-01 13:00:00,88.782933,90.381450,86.809100,81.652900,79.172516,75.591317,89.648884,83.418584,78.386050,79.714467,82.009567,85.335650
14,2021-03-01 14:00:00,86.393366,88.480834,85.196233,73.350167,77.318484,77.314834,88.824284,73.633501,77.743933,78.160450,73.960600,84.118400
15,2021-03-01 15:00:00,83.789633,86.686700,83.583400,82.157900,75.296333,76.449916,87.696450,70.342100,77.611033,76.530317,72.411550,74.907867
16,2021-03-01 16:00:00,81.389650,83.175133,82.229633,79.809100,73.378733,75.354967,86.540350,80.262883,77.104384,75.081584,70.795167,76.502633
17,2021-03-01 17:00:00,79.045466,73.082933,80.725766,84.297634,71.529666,73.867234,85.358250,86.072067,76.554933,73.786417,74.426683,71.652184
18,2021-03-01 18:00:00,77.041417,84.746450,79.187600,89.133334,71.489883,72.395650,84.212167,84.746833,76.072849,72.324999,85.879950,72.868717
19,2021-03-01 19:00:00,75.875633,84.961550,77.666150,86.663683,73.144100,77.729617,83.167066,74.785550,74.769849,71.776550,87.147100,84.977183
20,2021-03-01 20:00:00,85.891767,83.416050,81.395950,85.627150,71.387983,85.953666,86.879917,87.700717,73.544100,77.405033,86.763567,84.911883
21,2021-03-01 21:00:00,88.459067,86.845184,89.871451,84.618833,69.648301,84.256284,86.336000,84.342200,72.180416,83.721467,85.749450,88.251616
22,2021-03-01 22:00:00,87.571333,85.550083,88.846583,83.643484,80.497900,82.608600,85.067767,84.916933,75.521917,83.740700,84.462950,87.511950
23,2021-03-01 23:00:00,86.499317,84.280983,87.259917,82.947800,80.466550,81.088933,84.017950,93.770583,81.567783,82.171033,83.178550,86.485751

## 3. Przepływ inhibitorów

In [7]:
przeplyw = pd.read_excel(f'{folder_name}/3. Przepływ inhibitorów .xlsx', 
                         sheet_name='Inhibitory')
przeplyw

,Data,GODZINA,NaCl_przepływ_1_obieg,Klej_przepływ_1_obieg,Tiomocznik_przepływ_2_obieg,NaCl_przepływ_2_obieg,Klej_przepływ_2_obieg,Tiomocznik_przepływ_3_obieg,NaCl_przepływ_3_obieg,Klej_przepływ_3_obieg,...,Klej_przepływ_9_obieg,Tiomocznik_przepływ_10_obieg,NaCl_przepływ_10_obieg,Klej_przepływ_10_obieg,Tiomocznik_przepływ_11_obieg,NaCl_przepływ_11_obieg,Klej_przepływ_11_obieg,Tiomocznik_przepływ_12_obieg,NaCl_przepływ_12_obieg,Klej_przepływ_12_obieg
0,2021-03-01,23,8.31,20.98,27.12,8.27,33.77,16.92,4.20,20.01,...,26.93,22.47,49.99,26.92,22.81,16.75,27.32,22.79,50.01,27.46
1,2021-03-01,22,8.30,21.00,27.10,8.30,33.80,16.90,4.20,20.02,...,26.90,22.47,49.98,26.91,22.79,16.68,27.27,22.80,50.01,27.44
2,2021-03-01,21,8.29,21.01,27.06,8.35,33.80,16.93,4.20,19.99,...,26.86,22.51,50.00,26.88,22.78,16.73,27.31,22.79,50.01,27.45
3,2021-03-01,20,8.31,20.99,27.14,8.27,33.85,16.91,4.20,20.02,...,26.91,22.51,50.00,26.93,22.81,16.70,27.30,22.78,49.97,27.45
4,2021-03-01,19,8.30,20.97,27.10,8.30,33.84,16.89,4.20,20.01,...,26.90,22.46,50.00,26.89,22.80,16.69,27.30,22.84,50.00,27.50
5,2021-03-01,18,8.30,21.05,27.09,8.33,33.86,16.91,4.19,19.98,...,26.93,22.53,50.00,26.92,22.82,16.73,27.29,22.80,50.00,27.53
6,2021-03-01,17,8.30,20.99,27.08,8.28,33.81,16.91,4.19,20.02,...,26.90,22.55,50.01,26.89,22.81,16.68,27.28,22.78,50.00,27.54
7,2021-03-01,16,8.30,20.99,27.11,8.30,33.81,16.93,4.20,20.01,...,26.90,22.49,49.99,26.89,22.81,16.68,27.30,22.81,49.98,27.52
8,2021-03-01,15,8.30,21.02,27.11,8.31,33.80,16.87,4.20,20.00,...,26.91,22.52,50.03,26.88,22.80,16.73,27.34,22.78,50.02,27.54
9,2021-03-01,14,8.30,20.97,27.11,8.31,33.76,16.90,4.20,19.98,...,26.88,22.47,50.01,26.90,22.81,16.68,27.28,22.80,50.02,27.51
10,2021-03-01,13,8.31,14.34,27.09,8.30,33.80,16.92,4.20,13.50,...,17.74,22.51,50.00,17.71,22.78,16.70,17.92,22.81,49.98,27.50
11,2021-03-01,12,8.29,11.67,27.09,8.31,33.78,16.88,4.20,11.24,...,15.37,22.48,50.02,15.43,22.81,16.73,15.66,22.86,50.03,27.54
12,2021-03-01,11,8.30,21.00,27.08,8.31,33.79,16.89,4.19,20.01,...,26.97,22.12,48.58,26.92,22.81,16.66,27.28,22.79,50.04,27.56
13,2021-03-01,10,8.30,21.00,27.11,31.61,33.80,16.93,8.05,20.00,...,26.88,22.49,33.84,26.90,22.80,33.04,27.31,22.79,33.54,27.51
14,2021-03-01,9,8.30,20.98,27.09,33.30,33.81,16.90,8.30,20.01,...,26.91,22.52,33.27,26.90,22.77,33.30,27.30,22.85,33.30,27.51
15,2021-03-01,8,8.30,21.02,27.09,33.27,33.87,16.90,8.30,19.99,...,26.90,22.47,33.31,26.92,22.79,33.28,27.30,22.79,33.29,27.50
16,2021-03-01,7,8.29,21.00,27.14,33.30,33.81,16.90,8.30,20.00,...,26.93,22.53,33.31,26.88,22.80,33.30,27.32,22.78,33.34,27.61
17,2021-03-01,6,8.30,20.99,27.08,33.30,33.77,16.90,8.31,20.00,...,26.87,22.47,33.25,26.91,22.82,33.28,27.27,22.76,33.26,27.69
18,2021-03-01,5,8.31,21.00,27.09,33.31,33.80,16.50,8.29,19.50,...,26.29,22.03,33.32,26.28,22.78,33.32,27.33,22.84,33.33,27.68
19,2021-03-01,4,8.30,20.99,27.13,33.28,33.74,16.53,8.31,19.54,...,26.30,21.96,33.31,26.32,22.77,33.29,27.30,22.77,33.31,27.69
20,2021-03-01,3,8.31,20.98,27.09,33.30,33.74,16.50,8.30,19.48,...,26.32,22.05,33.30,26.31,22.81,33.27,27.28,22.83,33.27,27.66
21,2021-03-01,2,8.31,21.02,27.10,33.33,33.76,16.48,8.30,19.50,...,26.27,21.96,33.29,26.28,22.81,33.34,27.31,22.80,33.33,27.61
22,2021-03-01,1,8.31,20.97,27.12,33.27,33.76,16.51,8.29,19.52,...,26.34,22.02,33.32,26.30,22.78,33.26,27.31,22.78,33.29,27.60
23,2021-03-01,0,8.29,21.03,27.08,33.33,33.86,16.51,8.30,19.48,...,26.29,21.99,33.30,26.32,22.81,33.33,27.26,22.78,33.27,27.59

## 4. Komponowanie składu elektrolitu w obiegach cyrkulacyjnych - objętość i przepływ

In [8]:
objetosc_przeplyw = pd.read_excel(f'{folder_name}/4. Komponowanie składu elektrolitu w obiegach cyrkulacyjnych-objętość i przepływ.xlsx', 
                                  sheet_name='Komponowanie elektrolitu')
objetosc_przeplyw

,Data,obieg,kwas [m3],Kondensat [m3],Elektrolit [m3],NaCl [kg]
0,2021-03-01 00:00:00.000,1,3,0,-3,1.0
1,2021-03-01 00:00:00.000,2,1,24,-25,1.0
2,2021-03-01 00:00:00.000,3,0,0,0,0.5
3,2021-03-01 00:00:00.000,4,4,50,106,2.0
4,2021-03-01 00:00:00.000,5,0,0,0,5.5
5,2021-03-01 00:00:00.000,6,2,0,-2,2.0
6,2021-03-01 00:00:00.000,7,1,0,-1,6.0
7,2021-03-01 00:00:00.000,8,3,24,-27,6.0
8,2021-03-01 00:00:00.000,9,2,0,-2,5.5
9,2021-03-01 00:00:00.000,10,0,0,0,6.0
10,2021-03-01 00:00:00.000,11,1,32,47,2.0
11,2021-03-01 00:00:00.000,12,0,0,0,6.0

## 5. Natężenie prądu w obwodach prądowych

In [9]:
prad = pd.read_excel(f'{folder_name}/5. Natężenie prądu w obwodach prądowych.xlsx', 
                     sheet_name='Obwody prądowe')
prad

,Data/godzina,Obwód 1,Obwód 2,Obwód 3,Obwód 4,Obwód 5,Obwód 6
0,2021-03-01 00:00:00.000,13.06100,13.27600,13.32900,13.30000,13.14925,13.78475
1,2021-03-01 01:00:00.000,13.07625,13.27525,13.33700,13.30475,13.15325,13.79000
2,2021-03-01 02:00:00.000,13.07150,13.27600,13.33575,13.30425,13.15150,13.78725
3,2021-03-01 03:00:00.000,13.07050,13.27550,13.33550,13.30725,13.15300,13.79125
4,2021-03-01 04:00:00.000,13.04400,13.27125,13.33000,13.30150,13.15200,13.78600
5,2021-03-01 05:00:00.000,13.05000,13.57175,13.62975,13.60550,13.44725,13.79125
6,2021-03-01 06:00:00.000,13.06750,13.57000,13.63125,13.60450,13.44700,13.78625
7,2021-03-01 07:00:00.000,13.07575,13.57375,13.63575,13.61275,13.44875,13.79525
8,2021-03-01 08:00:00.000,13.07000,13.57350,13.63275,13.61325,13.45125,13.79250
9,2021-03-01 09:00:00.000,13.07150,13.57350,13.63475,13.61100,13.45700,13.79475
10,2021-03-01 10:00:00.000,13.06900,13.57000,13.62900,13.60975,13.45175,13.78650
11,2021-03-01 11:00:00.000,13.07650,13.57450,13.64100,13.61075,13.45150,13.78950
12,2021-03-01 12:00:00.000,13.07775,13.57425,13.63675,13.61225,13.45100,13.79375
13,2021-03-01 13:00:00.000,13.07625,13.57175,13.63525,13.61300,13.44850,13.79075
14,2021-03-01 14:00:00.000,13.05400,13.57400,13.63775,13.55425,13.45200,13.79450
15,2021-03-01 15:00:00.000,13.04800,13.52100,13.62900,13.61000,13.38400,13.76475
16,2021-03-01 16:00:00.000,13.04300,13.54225,13.59450,13.61075,13.45925,13.79250
17,2021-03-01 17:00:00.000,13.07450,13.58975,13.62225,13.59625,13.45150,13.76200
18,2021-03-01 18:00:00.000,13.07300,13.56675,13.63725,13.52950,13.45625,13.78675
19,2021-03-01 19:00:00.000,13.06075,13.56850,13.63125,13.59950,13.45250,13.77950
20,2021-03-01 20:00:00.000,13.06625,13.56925,13.63375,13.60175,13.45400,13.70125
21,2021-03-01 21:00:00.000,13.07300,13.57225,13.63775,13.60975,13.45000,13.78925
22,2021-03-01 22:00:00.000,13.07425,13.57050,13.63725,13.60400,13.45100,13.78975
23,2021-03-01 23:00:00.000,13.07100,13.56950,13.63925,13.60200,13.45000,13.79300

## 6. Spadek napięcia na grupach wanien elektrolitycznych

In [10]:
spadek_napiecie = pd.read_excel(f'{folder_name}/6. Spadek napięcia na grupach wanien elektrolitycznych.xlsx', 
                     sheet_name='Napiecie na grupach wanien')
spadek_napiecie

,Data,Grupa 1,Grupa 2,Grupa 3,Grupa 4,Grupa 5,Grupa 6,Grupa 7,Grupa 8,Grupa 9,...,Grupa 87,Grupa 88,Grupa 89,Grupa 90,Grupa 91,Grupa 92,Grupa 93,Grupa 94,Grupa 95,Grupa 96
0,2021-03-01 00:00:00.000,7.648701,5.675527,7.909787,7.402112,6.518906,5.993378,7.281869,7.074954,7.332835,...,6.867733,5.794244,5.297555,6.438490,6.985382,5.652486,7.075716,5.719474,7.659841,5.764641
1,2021-03-01 01:00:00.000,7.713706,5.722831,7.878048,7.365642,6.810053,7.366711,7.490921,7.282937,7.392499,...,6.698202,5.633564,5.292825,6.435133,6.989197,5.656453,6.987365,5.658589,7.844325,5.933103
2,2021-03-01 02:00:00.000,0.414136,5.656758,7.989898,7.480545,6.782128,0.469680,7.445143,7.242195,7.219459,...,6.972106,5.890530,5.318461,6.464278,6.965240,5.630665,6.998200,5.607318,7.773065,5.866726
3,2021-03-01 03:00:00.000,0.453200,5.796228,8.073672,7.559588,6.705527,0.459914,7.492446,7.280648,7.319559,...,6.943266,5.870540,5.335399,6.492966,7.196265,5.854213,7.060610,5.643483,7.851497,5.930357
4,2021-03-01 04:00:00.000,6.199377,5.556352,7.936643,7.430799,6.647236,7.313303,7.502365,7.286142,7.210456,...,6.799829,5.751366,5.350200,6.517685,7.112491,5.776086,7.215796,5.804621,7.742393,5.806451
5,2021-03-01 05:00:00.000,7.370678,5.630665,8.188116,7.679067,6.853694,7.346263,7.592700,7.336039,7.234413,...,6.630909,5.648213,5.325175,6.462752,7.256386,5.863674,7.224037,5.769982,7.679067,5.742668
6,2021-03-01 06:00:00.000,6.970885,5.537584,8.153935,7.681509,7.211066,7.475356,7.487106,7.342143,7.250588,...,6.688284,5.771050,5.427717,6.460311,7.160863,5.829493,7.126225,5.635548,7.679220,5.726951
7,2021-03-01 07:00:00.000,6.925413,5.480667,8.084811,7.496414,7.050997,7.418286,7.545244,7.442244,7.098300,...,6.609394,5.692770,5.493332,6.541643,7.172002,5.856350,7.135533,5.626087,7.750328,5.786767
8,2021-03-01 08:00:00.000,7.054506,5.498825,8.216346,7.641682,6.816309,7.153844,7.442397,7.341533,7.092196,...,6.683706,5.743736,5.408796,6.477096,7.026582,5.724967,7.255013,5.680562,7.579577,5.620136
9,2021-03-01 09:00:00.000,6.935179,5.325022,8.058565,7.551805,6.875973,6.821192,7.543413,7.404553,6.879940,...,6.542711,5.603198,5.295572,6.384320,7.081820,5.764641,7.232734,5.650502,7.700888,5.731681
10,2021-03-01 10:00:00.000,6.945860,5.356456,8.028809,7.502365,7.280343,7.184057,7.421644,7.391736,6.831721,...,6.551561,5.588550,5.253609,6.346324,6.885128,5.538346,7.224036,5.593280,7.543260,5.560320
11,2021-03-01 11:00:00.000,6.992706,5.331736,8.034455,7.401959,7.009491,6.794030,7.052980,7.075716,6.893216,...,6.666768,5.675680,5.112156,6.211585,6.836756,5.476394,6.943266,5.408948,7.567675,5.568102
12,2021-03-01 12:00:00.000,6.914121,5.356151,7.687918,7.033448,6.434065,6.373028,6.921598,6.895047,6.785485,...,6.697745,5.688955,5.093845,6.195257,6.823023,5.450911,6.931516,5.391247,7.444990,5.441603
13,2021-03-01 13:00:00.000,6.852016,5.371105,7.666097,7.023682,6.591540,6.474654,6.926328,6.908780,6.864986,...,6.471908,5.469069,5.187384,6.293985,6.878567,5.497757,6.992706,5.402997,7.506333,5.491806
14,2021-03-01 14:00:00.000,6.919462,5.552690,7.941221,7.299570,6.626179,6.545915,7.114933,7.131718,7.051607,...,6.809595,5.792413,5.169836,6.294290,6.889553,5.497604,7.089449,5.506913,7.602466,5.582446
15,2021-03-01 15:00:00.000,6.962645,5.624256,8.237251,7.591632,6.927702,6.842250,7.331461,7.376324,7.175207,...,6.735283,5.725120,5.348369,6.454817,7.031160,5.635700,7.113560,5.595721,7.663350,5.636616
16,2021-03-01 16:00:00.000,7.145604,5.815150,8.268380,7.628254,7.279580,7.141026,7.528306,7.547991,7.404553,...,6.948912,5.937529,5.228889,6.332896,7.027650,5.617084,7.613758,5.844295,7.792596,5.762810
17,2021-03-01 17:00:00.000,7.329478,5.920438,8.393353,7.754448,7.337260,7.219764,7.757500,7.753838,7.559435,...,7.192602,6.179235,5.618305,6.715751,7.439802,6.016572,7.295755,5.847041,7.867367,5.822321
18,2021-03-01 18:00:00.000,7.295297,5.937376,8.338420,7.703177,7.179022,7.079531,7.661367,7.633747,7.656789,...,7.250282,6.243782,5.591754,6.683401,7.548296,6.115146,7.450026,5.894497,8.040864,5.985595
19,2021-03-01 19:00:00.000,7.285226,5.890377,8.320566,7.687155,7.217170,7.097842,7.635731,7.597735,7.829524,...,6.796930,5.828425,5.556352,6.654561,7.488327,6.063722,7.470473,5.867031,8.122044,6.060518
20,2021-03-01 20:00:00.000,7.382733,5.989563,8.289896,7.661366,7.142247,7.039552,7.526169,7.468489,7.885220,...,7.062288,6.092105,5.655538,6.739402,7.475967,6.045564,7.681051,6.046785,8.097477,6.030305
21,2021-03-01 21:00:00.000,7.316202,5.903348,8.159123,7.538225,7.180395,7.039552,7.468642,7.403028,7.949461,...,6.917325,5.944090,5.552995,6.654256,7.505875,6.057314,7.530442,5.888852,8.027589,5.935850
22,2021-03-01 22:00:00.000,7.323679,5.930204,8.010499,7.394940,6.985381,6.894894,7.456893,7.386090,7.854854,...,6.874752,5.903806,5.534074,6.644032,7.393872,5.942869,7.268135,5.725272,7.994782,5.893887
23,2021-03-01 23:00:00.000,7.103946,5.690939,8.140965,7.518998,7.016663,6.944792,7.399671,7.340312,7.731864,...,7.191382,6.185186,5.530259,6.646321,7.414319,5.952178,7.374798,5.793634,8.106632,6.000854

## 7. Czas pracy,wydajność prądowa i zużycie energi elektrycznej (grupa produkcyjna 1-2;9-96 po zakończonej fazie

In [11]:
czas_wydajnosc_zuzycie = pd.read_excel(f'{folder_name}/7. Czas pracy,wydajność prądowa i zużycie energi elektrycznej (grupa produkcyjna 1-2;9-96 po zakończonej fazie.xlsx', 
                                       sheet_name='grupy')
czas_wydajnosc_zuzycie

,Grupa,Data,Uzysk,Czas,Waga katod( z podkładkami),Wydajność,kWh/t
0,27,2021-03-01,86.34,284.20,92609,99.18,290.29
1,32,2021-03-01,87.95,288.41,95052,100.42,271.15
2,85,2021-03-01,86.92,269.34,91342,98.97,298.26
3,18,2021-03-02,86.64,281.89,92065,99.28,289.12
4,36,2021-03-02,87.15,280.08,93065,100.46,285.78
5,37,2021-03-02,86.46,279.02,91646,99.05,303.48
6,72,2021-03-02,87.27,287.05,93282,99.48,274.32
7,9,2021-03-03,86.75,259.84,84260,99.44,291.03
8,13,2021-03-03,86.12,297.98,95331,98.71,294.44
9,33,2021-03-03,81.00,242.00,80902,99.95,321.52
10,53,2021-03-03,86.76,267.25,88430,99.55,303.39
11,76,2021-03-03,86.92,295.98,95514,98.66,278.28
12,28,2021-03-04,86.07,249.13,82280,99.53,296.78
13,40,2021-03-04,86.55,282.09,93062,99.21,290.91
14,48,2021-03-04,85.69,251.81,82625,98.08,303.68
15,60,2021-03-04,86.81,267.84,88842,99.62,286.29
16,26,2021-03-05,81.00,243.67,80296,98.95,331.19
17,79,2021-03-05,85.89,284.08,92896,99.37,286.36
18,80,2021-03-05,87.44,293.64,95660,99.30,290.75
19,91,2021-03-05,87.41,247.08,84614,99.56,300.54
20,12,2021-03-06,86.70,271.06,87619,99.31,285.82

## 8.9.11. Klasyfikacja jakościowa katod, skład chemiczny katod i anod w grupach(każda grupa produkcyjna-stosy)

In [12]:
klasyfikacja_grupy = pd.read_excel(f'{folder_name}/8.9.11. Klasyfikacja jakościowa katod, skład chemiczny katod i anod w grupach(każda grupa produkcyjna-stosy).xlsx', 
                                   sheet_name='Grupy produkcyjne')
klasyfikacja_grupy

,NUMER GRUPY,DATA ZAŁĄCZENIA GRUPY,DATA WYŁĄCZENIA GRUPY,TRYB,CYKL,MASA GRUPY,Klasyfikacja jakościowa katod,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,MASA WYTOPU,ENERGIA,WYDAJNOŚĆ
0,NaN,NaN,NaN,NaN,NaN,NaN,HMG-S,Cu- CATH 1 Z,Cu-CATH 2,Katody niesklasyfikowane,...,ANALIZA S,ANALIZA Sb,ANALIZA O2,ANALIZA Bi,ANALIZA Sn,ANALIZA Zn,ANALIZAAg,NaN,NaN,NaN
1,NaN,rrrr-mm-dd,rrrr-mm-dd,NaN,NaN,[kg],[stosy],[stosy],[stosy],[sztuki],...,[%],[%],[%],[%],[%],[%],[%],[Mg],[kWh],[%]
2,44.0,2021-03-01 04:57:19,2021-03-11 05:56:59,PROD,1.0,78295,38,0,4,0,...,0.0006,0.017,0.06,0.0043,0.0011,NaN,0.28,189.36,18077,95.99
3,65.0,2021-03-01 12:02:07,2021-03-13 18:28:09,PROD,2.0,97053,41,0,6,0,...,NaN,0.00945,0.053152,0.00015,0.006075,0.00765,NaN,189.849,27014,99.4
4,46.0,2021-03-01 15:05:40,2021-03-13 04:49:38,PROD,2.0,92272,45,0,2,0,...,0.0006,0.0075,0.1125,0.004425,0.0005,NaN,0.275,189.36,27351,98.51
5,81.0,2021-03-01 15:08:03,2021-03-13 10:59:50,PROD,2.0,96073,45,0,1,0,...,0.0006,0.0108,0.128,0.00466,0.0009,NaN,0.2645,189.36,28133,99.01
6,85.0,2021-03-01 20:50:11,2021-03-12 17:20:54,PROD,1.0,84553,36,0,8,0,...,0.0007,0.014,0.1,0.0048,0.0014,NaN,0.3,189.36,20461,95.05
7,27.0,2021-03-01 22:09:36,2021-03-12 05:57:00,PROD,1.0,81569,39,0,2,0,...,0.0006,0.01275,0.105,0.00425,0.00065,NaN,0.2875,189.36,19364,98.33
8,32.0,2021-03-01 23:10:25,2021-03-11 14:01:57,PROD,1.0,75935,37,0,2,0,...,0.0006,0.01375,0.0925,0.0042,0.0011,NaN,0.29,189.36,18210,97.68
9,38.0,2021-03-02 12:13:59,2021-03-13 01:51:34,PROD,2.0,85313,40,0,1,0,...,0.0006,0.01025,0.0875,0.0046,0.000275,NaN,0.3,189.36,24564,99.35
10,31.0,2021-03-02 14:46:42,2021-03-14 02:03:13,PROD,2.0,91160,45,0,1,0,...,0.0006,0.0055,0.11,0.00425,0.000275,NaN,0.2975,189.36,25943,98.97
11,54.0,2021-03-02 19:36:23,2021-03-14 01:56:16,PROD,2.0,90359,43,0,1,0,...,0.0006,0.01375,0.11,0.004825,0.0007,NaN,0.2675,189.36,26168,99.4
12,36.0,2021-03-02 22:04:23,2021-03-12 13:56:11,PROD,1.0,74820,40,0,4,0,...,0.0006,0.0105,0.105,0.0044,0.00065,NaN,0.295,189.36,17183,95.36
13,72.0,2021-03-02 22:04:58,2021-03-12 09:15:19,PROD,1.0,74264,38,0,2,0,...,0.0006,0.009,0.095,0.00435,0.0004,NaN,0.31,189.36,16789,97.67
14,61.0,2021-03-02 23:01:10,2021-03-14 09:01:59,PROD,2.0,91628,44,0,0,0,...,0.0006,0.009,0.1025,0.004425,0.000625,NaN,0.2925,189.36,27151,99.61
15,37.0,2021-03-03 02:19:34,2021-03-13 06:14:14,PROD,1.0,80168,40,0,2,0,...,0.0006,0.01125,0.0825,0.0044,0.000475,NaN,0.3125,189.36,19681,98.69
16,18.0,2021-03-03 06:57:05,2021-03-13 09:12:39,PROD,1.0,80210,42,0,2,0,...,0.0006,0.01045,0.1155,0.004025,0.000655,NaN,0.211,189.36,18718,99.02
17,96.0,2021-03-03 12:11:01,2021-03-15 15:58:15,PROD,2.0,98519,45,0,2,0,...,0.0006,0.01235,0.1495,0.004135,0.00057,NaN,0.214,189.36,28346,98.89
18,56.0,2021-03-03 19:45:06,2021-03-15 01:55:33,PROD,2.0,90173,46,0,1,0,...,0.0006,0.0105,0.0725,0.005225,0.0011,NaN,0.2875,189.36,25163,99.6
19,13.0,2021-03-03 22:04:54,2021-03-14 14:15:53,PROD,1.0,79455,39,0,1,0,...,0.0006,0.01,0.11,0.0041,0.0006,NaN,0.28,189.36,19225,96.66
20,53.0,2021-03-03 22:21:12,2021-03-15 09:23:24,PROD,1.0,90354,39,0,4,0,...,0.0006,0.011,0.1325,0.0044,0.00035,NaN,0.315,189.36,22155,99.05
21,76.0,2021-03-03 22:22:20,2021-03-13 14:05:12,PROD,1.0,75031,36,0,3,0,...,0.0006,0.013,0.115,0.00435,0.000475,NaN,0.3075,189.36,16678,97.49
22,2.0,2021-03-03 23:00:50,2021-03-14 22:53:17,PROD,2.0,85328,41,0,1,0,...,0.0006,0.00975,0.095,0.004425,0.000675,NaN,0.29,189.36,24011,99.28
23,33.0,2021-03-04 06:17:42,2021-03-14 17:25:03,PROD,1.0,82086,39,0,2,0,...,0.00064,0.0136,0.106,0.00448,0.00092,NaN,0.303,189.36,19440,97.6

In [13]:
produkcja_katody = pd.read_excel(f'{folder_name}/8.9.11. Klasyfikacja jakościowa katod, skład chemiczny katod i anod w grupach(każda grupa produkcyjna-stosy).xlsx', 
                                 sheet_name='Grupy produkcyjne')
produkcja_katody

,NUMER GRUPY,DATA ZAŁĄCZENIA GRUPY,DATA WYŁĄCZENIA GRUPY,TRYB,CYKL,MASA GRUPY,Klasyfikacja jakościowa katod,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,MASA WYTOPU,ENERGIA,WYDAJNOŚĆ
0,NaN,NaN,NaN,NaN,NaN,NaN,HMG-S,Cu- CATH 1 Z,Cu-CATH 2,Katody niesklasyfikowane,...,ANALIZA S,ANALIZA Sb,ANALIZA O2,ANALIZA Bi,ANALIZA Sn,ANALIZA Zn,ANALIZAAg,NaN,NaN,NaN
1,NaN,rrrr-mm-dd,rrrr-mm-dd,NaN,NaN,[kg],[stosy],[stosy],[stosy],[sztuki],...,[%],[%],[%],[%],[%],[%],[%],[Mg],[kWh],[%]
2,44.0,2021-03-01 04:57:19,2021-03-11 05:56:59,PROD,1.0,78295,38,0,4,0,...,0.0006,0.017,0.06,0.0043,0.0011,NaN,0.28,189.36,18077,95.99
3,65.0,2021-03-01 12:02:07,2021-03-13 18:28:09,PROD,2.0,97053,41,0,6,0,...,NaN,0.00945,0.053152,0.00015,0.006075,0.00765,NaN,189.849,27014,99.4
4,46.0,2021-03-01 15:05:40,2021-03-13 04:49:38,PROD,2.0,92272,45,0,2,0,...,0.0006,0.0075,0.1125,0.004425,0.0005,NaN,0.275,189.36,27351,98.51
5,81.0,2021-03-01 15:08:03,2021-03-13 10:59:50,PROD,2.0,96073,45,0,1,0,...,0.0006,0.0108,0.128,0.00466,0.0009,NaN,0.2645,189.36,28133,99.01
6,85.0,2021-03-01 20:50:11,2021-03-12 17:20:54,PROD,1.0,84553,36,0,8,0,...,0.0007,0.014,0.1,0.0048,0.0014,NaN,0.3,189.36,20461,95.05
7,27.0,2021-03-01 22:09:36,2021-03-12 05:57:00,PROD,1.0,81569,39,0,2,0,...,0.0006,0.01275,0.105,0.00425,0.00065,NaN,0.2875,189.36,19364,98.33
8,32.0,2021-03-01 23:10:25,2021-03-11 14:01:57,PROD,1.0,75935,37,0,2,0,...,0.0006,0.01375,0.0925,0.0042,0.0011,NaN,0.29,189.36,18210,97.68
9,38.0,2021-03-02 12:13:59,2021-03-13 01:51:34,PROD,2.0,85313,40,0,1,0,...,0.0006,0.01025,0.0875,0.0046,0.000275,NaN,0.3,189.36,24564,99.35
10,31.0,2021-03-02 14:46:42,2021-03-14 02:03:13,PROD,2.0,91160,45,0,1,0,...,0.0006,0.0055,0.11,0.00425,0.000275,NaN,0.2975,189.36,25943,98.97
11,54.0,2021-03-02 19:36:23,2021-03-14 01:56:16,PROD,2.0,90359,43,0,1,0,...,0.0006,0.01375,0.11,0.004825,0.0007,NaN,0.2675,189.36,26168,99.4
12,36.0,2021-03-02 22:04:23,2021-03-12 13:56:11,PROD,1.0,74820,40,0,4,0,...,0.0006,0.0105,0.105,0.0044,0.00065,NaN,0.295,189.36,17183,95.36
13,72.0,2021-03-02 22:04:58,2021-03-12 09:15:19,PROD,1.0,74264,38,0,2,0,...,0.0006,0.009,0.095,0.00435,0.0004,NaN,0.31,189.36,16789,97.67
14,61.0,2021-03-02 23:01:10,2021-03-14 09:01:59,PROD,2.0,91628,44,0,0,0,...,0.0006,0.009,0.1025,0.004425,0.000625,NaN,0.2925,189.36,27151,99.61
15,37.0,2021-03-03 02:19:34,2021-03-13 06:14:14,PROD,1.0,80168,40,0,2,0,...,0.0006,0.01125,0.0825,0.0044,0.000475,NaN,0.3125,189.36,19681,98.69
16,18.0,2021-03-03 06:57:05,2021-03-13 09:12:39,PROD,1.0,80210,42,0,2,0,...,0.0006,0.01045,0.1155,0.004025,0.000655,NaN,0.211,189.36,18718,99.02
17,96.0,2021-03-03 12:11:01,2021-03-15 15:58:15,PROD,2.0,98519,45,0,2,0,...,0.0006,0.01235,0.1495,0.004135,0.00057,NaN,0.214,189.36,28346,98.89
18,56.0,2021-03-03 19:45:06,2021-03-15 01:55:33,PROD,2.0,90173,46,0,1,0,...,0.0006,0.0105,0.0725,0.005225,0.0011,NaN,0.2875,189.36,25163,99.6
19,13.0,2021-03-03 22:04:54,2021-03-14 14:15:53,PROD,1.0,79455,39,0,1,0,...,0.0006,0.01,0.11,0.0041,0.0006,NaN,0.28,189.36,19225,96.66
20,53.0,2021-03-03 22:21:12,2021-03-15 09:23:24,PROD,1.0,90354,39,0,4,0,...,0.0006,0.011,0.1325,0.0044,0.00035,NaN,0.315,189.36,22155,99.05
21,76.0,2021-03-03 22:22:20,2021-03-13 14:05:12,PROD,1.0,75031,36,0,3,0,...,0.0006,0.013,0.115,0.00435,0.000475,NaN,0.3075,189.36,16678,97.49
22,2.0,2021-03-03 23:00:50,2021-03-14 22:53:17,PROD,2.0,85328,41,0,1,0,...,0.0006,0.00975,0.095,0.004425,0.000675,NaN,0.29,189.36,24011,99.28
23,33.0,2021-03-04 06:17:42,2021-03-14 17:25:03,PROD,1.0,82086,39,0,2,0,...,0.00064,0.0136,0.106,0.00448,0.00092,NaN,0.303,189.36,19440,97.6

## 10. Skład chemiczny elektrolitu cyrkulacyjnego

In [14]:
TO DO!!!!!!!!!!!!!!!!!!

SyntaxError: invalid syntax (<ipython-input-14-176e55b92a1c>, line 1)

In [ ]:
sklad_elektrolitu = pd.read_excel(f'{folder_name}/8.9.11. Klasyfikacja jakościowa katod, skład chemiczny katod i anod w grupach(każda grupa produkcyjna-stosy).xlsx', 
                                  sheet_name='Grupy produkcyjne')
sklad_elektrolitu

# Przygotowanie danych

# Eksploracyjna Analiza Danych